name: Docker Image CI

on:
  push:
    branches: 
      - "main"
env:
  REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
  API_KEY: ${{ secrets.API_KEY }}
  DOCKER_USER:  ${{ secrets.DOCKERHUB_LOGIN }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Login to DockerHub
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD    
    - name: Get date
      id: date
      run: |
        echo "{date}={$(date +'%Y%m%d-%M%S')}" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jakestec/humidity_monitor:latest_arm64 --build-arg api_key=$API_KEY --build-arg refresh_token=$REFRESH_TOKEN
    - name: Push the Docker image
      run: docker push jakestec/humidity_monitor:latest_arm64
