name: Docker Image CI

on:
  push:
    branches: 
      - "main"
env:
  BUILD_DATE: $(date +'%Y%m%d-%M%S')
  REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
  API_KEY: ${{ secrets.API_KEY }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Get date
      id: date
      run: |
        echo "{date}={$(date +'%Y%m%d-%M%S')}" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --platform linux/arm64/v8 --file Dockerfile --tag jakestec/humidity_monitor:latest_arm64-${{ env.date }} --build-arg api_key=$API_KEY --build-arg refresh_token=$REFRESH_TOKEN
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_LOGIN }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push the Docker image
      run: docker push jakestec/humidity_monitor:latest_arm64-${{ env.date }}
